Colorize output using termcolor
meritlabs/libmeritminer pull request #15
Opened 2018-08-29 03:30 UTC by jostrander

Hey team! I hope this is a welcomed change and that it isn't too much at once.

Due to having tried tracking error messages down, etc when the miner is running I did some cleanup work and added [termcolor](https://github.com/ikalnytskyi/termcolor) for colorized outputs.

I added red coloring to all `std::cerr` error messages, and made sure all errors are sent to the error stream. Also changed most informational messages to use the standard `std::cout` stream so that the two streams can be directed to different outputs, which makes it easy to filter out only errors. 

I also colorized a few things that users may find important including stats, difficulty, stratum messages and other numeric information. 

I've only compiled this on linux, without an nvidia device present, but here's an example of what to expect:
![image](https://user-images.githubusercontent.com/760989/44763646-30bd1e80-ab1a-11e8-91e0-8238d9354753.png)

2018-08-31 19:32 UTC, jostrander commented
@mempko Any interest in this, should I rebase or not bother?

2018-09-03 07:22 UTC, Retsediv requested changes
Awesome job, @jostrander ! 
I have resolved merge conflict and just a few comments left
The master branch has been updated since your PR, so, please, look at meritd.cpp(line 98 and 106) and public.cpp(line 130). There are std::cerr with no coloring

2018-09-03 07:22 UTC, Retsediv commented on src/miner/miner.cpp
> +                                    std::cout << "mining worker " << id << " error: " << e.what() << std::endl;
This is an error, so use std::cerr with red colour as everywhere else

2018-09-03 07:22 UTC, Retsediv commented on src/minerd.cpp
> +        std::cerr << "forgot to set your reward address. use --address" << std::endl;
You forgot to set the red colour here and you shouldn't change the text. Bring it back to the 
 
> forgot to set your reward address. Use -a or --address

(because we have both variants with -a and --address)

2018-09-03 07:22 UTC, Retsediv commented on src/public.cpp
> +        std::cout << "info :: " << "connecting to: " << url << termcolor::reset << std::endl;
You did not use any colour here but reset termcolor

2018-09-03 13:47 UTC, jostrander commented on src/minerd.cpp
> +        std::cerr << "forgot to set your reward address. use --address" << std::endl;
I can change this back, but it appears you merged this change in (removing -a). https://github.com/jostrander/libmeritminer/commit/90df43bfd7ac964c12d67848785da93926fb2d92#diff-26e515ef7ebd717f4620b732a9ff890dR94

2018-09-03 13:49 UTC, jostrander commented on src/minerd.cpp
> +        std::cerr << "forgot to set your reward address. use --address" << std::endl;
Nevermind, it just got lost in the rebase. I'll just add it back.

2018-09-03 14:43 UTC, jostrander commented
Pushed up those changes  you requested @Retsediv

2018-09-03 14:47 UTC, Retsediv approved these changes

2018-09-03 14:49 UTC, Retsediv commented
Thank you, @jostrander ! Great job is done!

2018-09-03 14:49 UTC, merged